### ISSUE TITLE
Labels on map still rotating after installing the package

### ISSUE THREAD

**Issue by rithvikhashclude** [greensopinion/flutter-vector-map-tiles#160] opened 2023-06-08 10:19 UTC
Hi,
I found this plugin from: https://docs.fleaflet.dev/explanation/raster-vs-vector-tiles.
I have installed the plugin into my application. But the labels are still rotating with the map. How do I fix this issue?

**Comment by greensopinion** [comment] 2023-06-09 14:51
duplicate of #107

**Closed by greensopinion** 2023-06-09 14:51 UTC
