### ISSUE TITLE
Artifacts between tiles

### ISSUE THREAD

**Issue by JulianBissekkou** [greensopinion/flutter-vector-map-tiles#42] opened 2022-04-19 10:00 UTC
I checked out the example project and added my custom urlTemplate and style.
The map renders streets and text, but the tiles is cutting off content.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/36447137/163979853-b083f743-d2b1-4361-85ca-d0219a9d81a0.png">

Here is the code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_map/plugin_api.dart';
import 'package:latlong2/latlong.dart';
import 'package:map_test/dark_theme.dart';
import 'package:vector_map_tiles/vector_map_tiles.dart';
import 'package:vector_tile_renderer/src/themes/light_theme.dart';
import 'package:vector_tile_renderer/vector_tile_renderer.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _isDarkMode = true;
  final _lightTheme = ThemeReader().read(lightThemeData());
  final _darkTheme = ThemeReader().read(darkThemeData);

  static const urlTemplate =
      "https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_v2/VectorTileServer/tile/{z}/{x}/{y}.pbf";

  @override
  Widget build(BuildContext context) {
    final centerMunich = LatLng(48.129710, 11.586124);

    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(
            onPressed: () => setState(() => _isDarkMode = !_isDarkMode),
            icon: Icon(_isDarkMode ? Icons.dark_mode : Icons.light_mode),
          ),
        ],
      ),
      body: FlutterMap(
        options: MapOptions(
          center: centerMunich,
          zoom: 13.0,
          plugins: [VectorMapTilesPlugin()],
        ),
        layers: [
          VectorTileLayerOptions(
            theme: _isDarkMode ? _darkTheme : _lightTheme,
            tileProviders: TileProviders(
              {
                'esri': MemoryCacheVectorTileProvider(
                  delegate: NetworkVectorTileProvider(
                    urlTemplate: urlTemplate,
                    maximumZoom: 14,
                  ),
                  maxSizeBytes: 1024 * 1024 * 2,
                ),
              },
            ),
          ),
          MarkerLayerOptions(
            markers: [
              Marker(
                width: 80.0,
                height: 80.0,
                point: centerMunich,
                builder: (ctx) => Icon(
                  Icons.location_on_outlined,
                  color: _isDarkMode ? Colors.white : Colors.black,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
```

Here is the json for the dark theme:
The content for `final _darkTheme = ThemeReader().read(darkThemeData);` can be found here:
https://gist.github.com/JulianBissekkou/527d0ade9d4d0a87af9fc9198ad5f94a

**Comment by greensopinion** [comment] 2022-04-22 15:55
Thanks for the issue. I've had a quick look at the theme, it looks like there are some expressions in there that weren't supported until recently. See the [vector_tile_renderer changelog](https://pub.dev/packages/vector_tile_renderer/changelog) for details. 

You might want to pull the latest from this repository and try again. If you do, please attach a screenshot if it's any different. Theme expression support still isn't 100% so there could still be issues.

**Comment by greensopinion** [comment] 2022-04-29 00:23
closing, but feel free to reopen if there are specific issues that you are having

**Closed by greensopinion** 2022-04-29 00:23 UTC

**Comment by JulianBissekkou** [comment] 2022-05-06 09:50
I updated the lib to 1.5.0 which was release 5 days ago and I still have the same artifacts.
What expressions are not supported yet? Is there a way to contribute or to remove the unsupported expressions for now?

**Comment by greensopinion** [comment] 2022-05-07 14:52
Thanks for the update. You can see the result of new expression support in the [gallery](https://github.com/greensopinion/flutter-vector-map-tiles/blob/main/gallery/gallery.md). The process that I used to add support for new expressions was to load  a map with the theme, with a breakpoint in [UnsupportedExpression](https://github.com/greensopinion/dart-vector-tile-renderer/blob/f191b5d5fb5405620d6e84b38bfa6e31f12cc8c1/lib/src/themes/expression/expression.dart#L62) which is used for expressions that aren't recognized. 

There's a chance that the problem is a mismatch between the theme and the tiles. That one is harder to troubleshoot since the theme might be fine, but just doesn't select any data from the tileset because the tiles are structured differently. One way to double check is to load your theme and tileset into an editor like [maputnik](https://maputnik.github.io/) to see if you get a different result.

To get an idea of what's involved, here a a couple examples of pull requests that improve support for expressions:

* https://github.com/greensopinion/dart-vector-tile-renderer/pull/21
* https://github.com/greensopinion/dart-vector-tile-renderer/pull/22

**Comment by JulianBissekkou** [comment] 2022-05-09 05:14
I added a breakpoint in `UnsupportedExpression.evaluate` and I also added a breakpoint in `ExpressionParser._expressionChecked` where the `UnsupportedExpression` is created.

Both breakpoints where never called and the map was renders as shown in the screenshot. Looks like its another problem 🤔

**Comment by greensopinion** [comment] 2022-05-10 15:44
Great! What was the problem?

**Comment by tashi146** [comment] 2022-06-01 15:20
Hi @greensopinion, Thanks for the quick response. I have created the issue for this [here](https://github.com/greensopinion/flutter-vector-map-tiles/issues/56). Esri map is pretty common here. If you have a chance to look at this issue. It would be great.
