### ISSUE TITLE
How increase performance?

### ISSUE THREAD

**Issue by samatzhusup** [greensopinion/flutter-vector-map-tiles#20] opened 2021-12-13 10:07 UTC
in San Francisco and other cities map lags

https://user-images.githubusercontent.com/50781959/145792539-9c91d7cb-70e5-4940-859f-a61dedc52bf1.mp4

**Comment by greensopinion** [comment] 2021-12-13 16:32
Thanks for the issue. You'll find discussion and tips related to this topic on issue #10 

Closing as a duplicate of #10

**Closed by greensopinion** 2021-12-13 16:32 UTC
